# Generated by Django 4.0.3 on 2022-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_category_alter_item_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='old_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
