# Generated by Django 4.0.3 on 2022-06-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_exp_date', models.DateField()),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('max_orders', models.IntegerField()),
                ('discount_value', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
