# Generated by Django 4.0.3 on 2022-06-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='save',
            field=models.BooleanField(default=False),
        ),
    ]
