# Generated by Django 4.0.3 on 2022-03-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_category_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Price',
            field=models.PositiveIntegerField(),
        ),
    ]
