# Generated by Django 4.0.3 on 2022-03-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Price',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
