# Generated by Django 4.0.3 on 2022-06-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_promocode_max_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='save',
            new_name='save_info',
        ),
    ]
