# Generated by Django 4.0.3 on 2022-03-16 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_alter_cart_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='OrderItem',
        ),
    ]
