# Generated by Django 4.0.3 on 2022-03-16 16:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_cart_delete_orderitem_alter_order_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='OrderItem',
        ),
    ]
