# Generated by Django 4.0.3 on 2022-03-19 22:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_rename_orderitem_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='OrderItem',
        ),
    ]
