# Generated by Django 4.0.3 on 2022-03-27 15:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=256)),
                ('apartment_address', models.CharField(max_length=256)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('zip_code', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(5, "ZIP code can' be more than 5 numbers"), django.core.validators.MinLengthValidator(5, "ZIP code can't be less than 5 numbers")])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
